language:
  node_js
node_js:
  - "7.10.1"
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install --dev
  - npm install -g codecov
script:
  - npm run lint
  - npm run test-coverage
  - npm run report-coverage
